### ISSUE TITLE
Playbooks using this module fail with the new statuscake API

### ISSUE THREAD

**Issue by danhul** [labynocle/ansible-statuscake#12] opened 2022-08-25 12:01 UTC
Statuscake has announced they are deprecating the existing API by the end of next month and provided a new API. Do you consider updating this module to work with the new API?

**Comment by danhul** [comment] 2022-08-25 12:03
https://www.statuscake.com/api/v1/

**Comment by labynocle** [comment] 2022-08-25 14:09
hi @danhul 

oh thank you.
I didn't notice it...  I will try to take the time to update it but I guess the API probably has change a lot so I can't give you an ETA about it.

**Comment by danhul** [comment] 2022-08-25 14:15
Hi @labynocle Thanks for the fast and prompt response. I highly appreciate that you consider updating the module. 
Have checked online and there are no other modules available for statuscake.

**Comment by labynocle** [comment] 2022-08-28 18:23
Hi @danhul 

I started a MR (cf: [feat: use APIv1](https://github.com/labynocle/ansible-statuscake/pull/13) - in the branch [feat/api_v1](https://github.com/labynocle/ansible-statuscake/tree/feat/api_v1)) and you have a first draft of `status_cake_uptime.py` that you should be able to use (please note the doc to know the new options names are not ready).

However please note when you update a test you will always see the result as `changed` :disappointed: ...

If you can test and give me some feedbacks it will be great. :pray: 

I try to do my best to update and test everything before the deadline :+1:

**Comment by danhul** [comment] 2022-08-31 15:57
Hi @labynocle Thanks for the update. I have to change other playbooks and configuration files to match the changes for the module and it took me some time. I get error messages when I test my previous play book due to some parameters like: contact, status_codes, and follow_redirect. I will test by disabling this parameters and let you know, in the mean time please update me if these parameters can still be used with the updated module?

**Comment by labynocle** [comment] 2022-08-31 16:05
@danhul  :wave: 

yes I will push as soon as possible the updated doc with the new name of the params etc...
I'm really sorry you met some errors, I hope the next commits will fix them :pray:

**Comment by labynocle** [comment] 2022-08-31 17:10
I hope with this new version of the [README](https://github.com/labynocle/ansible-statuscake/tree/feat/api_v1#status_cake_uptime--example-usage), you will find all the right option names

let me know if you met some issues

@ArcRiiad if you have time we could probably test it together?

**Comment by ArcRiiad** [comment] 2022-08-31 17:51
> I hope with this new version of the [README](https://github.com/labynocle/ansible-statuscake/tree/feat/api_v1#status_cake_uptime--example-usage), you will find all the right option names
> 
> let me know if you met some issues
> 
> @ArcRiiad if you have time we could probably test it together?

We can give it a try during this week for sure 👌

**Comment by labynocle** [comment] 2022-09-05 19:09
Hi @danhul :wave: 

Did you test again? :)
With @ArcRiiad we launched a bench of tests with success!

Let me know if you still have issues (the [README](https://github.com/labynocle/ansible-statuscake/tree/feat/api_v1#status_cake_uptime--example-usage) is uptodate) but we should be able to merge it soon :pray:

**Comment by danhul** [comment] 2022-09-08 20:03
Hi @labynocle I am getting this error when running the playbook that uses this module. Any idea?

```
Traceback (most recent call last):
  File "/home/ansible/.local/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/ansible/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/ansible/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ansible/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/ansible/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/ansible/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/home/ansible/.local/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/ansible/.local/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0xffff97117b80>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ansible/.local/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/ansible/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/ansible/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.statuscake.com', port=443): Max retries exceeded with url: /v1/uptime?limit=100&page=2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff97117b80>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ansible/.ansible/tmp/ansible-tmp-1662646379.922341-947-60130818375923/AnsiballZ_status_cake_uptime.py", line 100, in <module>
    _ansiballz_main()
  File "/home/ansible/.ansible/tmp/ansible-tmp-1662646379.922341-947-60130818375923/AnsiballZ_status_cake_uptime.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ansible/.ansible/tmp/ansible-tmp-1662646379.922341-947-60130818375923/AnsiballZ_status_cake_uptime.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.status_cake_uptime', init_globals=dict(_module_fqn='ansible.modules.status_cake_uptime', _modlib_path=modlib_path),
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_status_cake_uptime_payload_p4hv2a2v/ansible_status_cake_uptime_payload.zip/ansible/modules/status_cake_uptime.py", line 190, in <module>
  File "/tmp/ansible_status_cake_uptime_payload_p4hv2a2v/ansible_status_cake_uptime_payload.zip/ansible/modules/status_cake_uptime.py", line 186, in main
  File "/tmp/ansible_status_cake_uptime_payload_p4hv2a2v/ansible_status_cake_uptime_payload.zip/ansible/modules/status_cake_uptime.py", line 97, in manage_test
  File "/tmp/ansible_status_cake_uptime_payload_p4hv2a2v/ansible_status_cake_uptime_payload.zip/ansible/modules/status_cake_uptime.py", line 64, in check_if_exist
  File "/tmp/ansible_status_cake_uptime_payload_p4hv2a2v/ansible_status_cake_uptime_payload.zip/ansible/modules/status_cake_uptime.py", line 55, in check_if_exist
  File "/home/ansible/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/ansible/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ansible/.local/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ansible/.local/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/ansible/.local/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.statuscake.com', port=443): Max retries exceeded with url: /v1/uptime?limit=100&page=2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff97117b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
failed: [single -> localhost] (item={'name': '<test-server-name>', 'url': 'https://<url-of-our-site>', 'contact': 'low-urgency'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "contact": "low-urgency",
        "name": "<test-server-name>",
        "url": "https://<url-of-our-site>"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/ansible/.local/lib/python3.8/site-packages/urllib3/connection.py\", line 174, in _new_conn\n    conn = connection.create_connection(\n  File \"/home/ansible/.local/lib/python3.8/site-packages/urllib3/util/connection.py\", line 95, in create_connection\n    raise err\n  File \"/home/ansible/.local/lib/python3.8/site-packages/urllib3/util/connection.py\", line 85, in create_connection\n    sock.connect(sa)\nConnectionRefusedError: [Errno 111] Connection refused\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/ansible/.local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 703, in urlopen\n    httplib_response = self._make_request(\n  File \"/home/ansible/.local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 386, in _make_request\n    self._validate_conn(conn)\n  File \"/home/ansible/.local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 1040, in _validate_conn\n    conn.connect()\n  File \"/home/ansible/.local/lib/python3.8/site-packages/urllib3/connection.py\", line 358, in connect\n    self.sock = conn = self._new_conn()\n  File \"/home/ansible/.local/lib/python3.8/site-packages/urllib3/connection.py\", line 186, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0xffff97117b80>: Failed to establish a new connection: [Errno 111] Connection refused\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/ansible/.local/lib/python3.8/site-packages/requests/adapters.py\", line 489, in send\n    resp = conn.urlopen(\n  File \"/home/ansible/.local/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 785, in urlopen\n    retries = retries.increment(\n  File \"/home/ansible/.local/lib/python3.8/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.statuscake.com', port=443): Max retries exceeded with url: /v1/uptime?limit=100&page=2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff97117b80>: Failed to establish a new connection: [Errno 111] Connection refused'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1662646379.922341-947-60130818375923/AnsiballZ_status_cake_uptime.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1662646379.922341-947-60130818375923/AnsiballZ_status_cake_uptime.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1662646379.922341-947-60130818375923/AnsiballZ_status_cake_uptime.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.status_cake_uptime', init_globals=dict(_module_fqn='ansible.modules.status_cake_uptime', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_status_cake_uptime_payload_p4hv2a2v/ansible_status_cake_uptime_payload.zip/ansible/modules/status_cake_uptime.py\", line 190, in <module>\n  File \"/tmp/ansible_status_cake_uptime_payload_p4hv2a2v/ansible_status_cake_uptime_payload.zip/ansible/modules/status_cake_uptime.py\", line 186, in main\n  File \"/tmp/ansible_status_cake_uptime_payload_p4hv2a2v/ansible_status_cake_uptime_payload.zip/ansible/modules/status_cake_uptime.py\", line 97, in manage_test\n  File \"/tmp/ansible_status_cake_uptime_payload_p4hv2a2v/ansible_status_cake_uptime_payload.zip/ansible/modules/status_cake_uptime.py\", line 64, in check_if_exist\n  File \"/tmp/ansible_status_cake_uptime_payload_p4hv2a2v/ansible_status_cake_uptime_payload.zip/ansible/modules/status_cake_uptime.py\", line 55, in check_if_exist\n  File \"/home/ansible/.local/lib/python3.8/site-packages/requests/api.py\", line 73, in get\n    return request(\"get\", url, params=params, **kwargs)\n  File \"/home/ansible/.local/lib/python3.8/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/home/ansible/.local/lib/python3.8/site-packages/requests/sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/home/ansible/.local/lib/python3.8/site-packages/requests/sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File \"/home/ansible/.local/lib/python3.8/site-packages/requests/adapters.py\", line 565, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.statuscake.com', port=443): Max retries exceeded with url: /v1/uptime?limit=100&page=2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff97117b80>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}`
```

**Comment by danhul** [comment] 2022-09-08 21:05
Running the same playbook again generates another error message 

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: Invalid header value b'Bearer <our-statuscake-api-key>\n'`.

**Comment by labynocle** [comment] 2022-09-09 06:59
Hi @danhul 

in your first trace it seems to be related you're not able to "contact" `api.statuscake.com` on port `443` from where the action took place

your second error seems to be related to the value you set for `api_key`, can you confirm the value you use allow you to run something like: 

```
curl https://api.statuscake.com/v1/uptime \
  -H "Authorization: Bearer ${API_TOKEN}"
```

can you describe the part of your playbook? (without the secret of course :pray: )
let me know but on my side everything seems ok and I think we are close to merge this PR

**Comment by danhul** [comment] 2022-09-09 08:21
The curl command works most of the time when I run it to get list of hosts and contact-groups(sometimes it fails with `curl: (28) Failed to connect to api.statuscake.com port 443 after 75006 ms: Operation timed out` error message). So the `API_KEY` is working and `api.statuscake.com` is also reachable. May be it is the rate limiting that makes the commands to fail sometimes?

I also attached the playbook here, for your easy reference (it's in txt format because .yml files can not be uploaded). 
[statuscake.txt](https://github.com/labynocle/ansible-statuscake/files/9533662/statuscake.txt)

**Comment by danhul** [comment] 2022-09-09 08:30
@labynocle FYI: When I run the playbook today, it returns

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.statuscake.com', port=443): Max retries exceeded with url: /v1/uptime?limit=100&page=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff8cc79550>: Failed to establish a new connection: [Errno 111] Connection refused'))`

**Comment by labynocle** [comment] 2022-09-09 11:51
@danhul to be honest the described error doesn't seem related to the script and according to the [official doc](https://www.statuscake.com/api/v1/#section/Ratelimits) the rate limits seems "fair" (maximum of 10 requests per second) and even if you reach it you should have a `429` http status. But do you think you could reach it?

Thank you for your config and everything seems ok

* Is it a reproducible pattern?
* Does it work at least one time?
* How many tests do you have in `status_cake_tests` and how many tests are already registered on statuscake? (because we could launch a lot of requests to find in the registered tests a test with the same name of the current tests... but I already use the max value for the `limit` :( )

Let me know!

**Comment by danhul** [comment] 2022-09-09 15:03
@labynocle 

- `Is it a reproducible pattern? ` yes, the playbook fails on every node I applied it to.
- `Does it work at least one time? `No
- `How many tests do you have in status_cake_tests and how many tests are already registered on statuscake? (because we could launch a lot of requests to find in the registered tests a test with the same name of the current tests... but I already use the max value for the limit :( )` : we have more than  200 tests. Which were added with the previous API. But I couldn't yet add any new test.


This line in the error message is strange, 
`Invalid header value b'Bearer *********************\n'`

In your module, I see that you put the Authorization header this way and it is not clear why ansible find it wrong
```

        self.headers = {
            "Authorization": "Bearer " + api_key,
            "Content-Type": "application/x-www-form-urlencoded"
        }

```

**Comment by labynocle** [comment] 2022-09-11 17:40
@danhul, sorry for the lag :wave: 

just to be sure when you said `he playbook fails on every node I applied it to`, can you confirm you can reach from them `api.statuscake.com:443` ? (with a `telnet` just to confirm you cam reach the API - the output lets suppose you can't)

can you remember me:

* the python version installed on your ansible nodes?
* the version of `requests`?
* confirm `statuscake_new_api_key` is well set?

on my side I currently use [these requierements](https://github.com/labynocle/ansible-statuscake/pull/13/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552) with python `v3.8.13`


(I made some other tests with success :thinking: so I'm a little confused about your context with the details you gave)

When we run tests with @ArcRiiad , we worked on a statuscake account with more than 1300 tests, so I guess 200 is not a problem

**Comment by danhul** [comment] 2022-09-12 12:36
@labynocle The problem seems to be related to the api_key. When I start testing this new module I generated a new api key on statuscake. This newly generated api_key works when I set it as env variable and run curl commands to api.statuscake.com using it without any problem. 
But for some reason it is failing to work on the playbook. I tested the playbook today with the existing (old) api_key and it works, so this issue is solved. 

But I encounter another problem :). The test on statuscake is missing "Contact Groups". If you can have a look at the playbook I sent you last week, it checks if contact is set or not and validates the value to be one of the two contacts we use. 
It then sets the "contact_groups" parameter as follows

`contact_groups: "{{ statuscake_contact_critical if item.contact == 'critical' else statuscake_contact_low_urgency if item.contact == 'low-urgency' }}"`

But the module doesn't set the contact group when adding the test in statuscake. Any idea?

**Comment by labynocle** [comment] 2022-09-12 17:53
@danhul :wave: 

happy to read one problem is solved! :+1: 

yes I remembered this config.

* can you confirm the current values of `statuscake_contact_critical` and `statuscake_contact_low_urgency`?
* is it consistent with the result of `curl https://api.statuscake.com/v1/contact-groups \
  -H "Authorization: Bearer ${API_TOKEN}"`?

**Comment by danhul** [comment] 2022-09-12 21:25
That's right @labynocle , am also happy to get it work.  👍 

Regarding contact-groups
`can you confirm the current values of statuscake_contact_critical and statuscake_contact_low_urgency?` The values of these two items are 
- statuscake_contact_critical: "119330"
- statuscake_contact_low_urgency: "181384"

`is it consistent with the result of curl https://api.statuscake.com/v1/contact-groups \ -H "Authorization: Bearer ${API_TOKEN}"?` this command outputs two contact-groups with IDs "181384" and "119330".

**Comment by labynocle** [comment] 2022-09-16 15:11
I have the explanation for the `contact_groups` issue... the parameters used by the plugin has been dropped by Statuscake (cf `contact_groups_csv`)
It was marked as deprecated but I didn't think it will be dropped now.

It's the same issue for `tags_cvs`

Let's see how we could change these settings

**Comment by labynocle** [comment] 2022-09-16 16:13
@danhul can you test it again with the latest version of the plugin? this commit (cf: [fix: remove and replace deprecated parameter ](https://github.com/labynocle/ansible-statuscake/pull/13/commits/6a74f97f8d014d4679da3492ce86ed98e53f4863)) should fix your current issue

**Comment by danhul** [comment] 2022-09-19 11:08
@labynocle contact_groups are set now by the module. Thank you very much for taking the time to address the issues.

**Comment by labynocle** [comment] 2022-09-19 15:37
@danhul thank you for all your tests... I guess we can merge the related MR soon !!

**Comment by danhul** [comment] 2022-09-20 07:29
Sure! You have already addressed the critical parts.

**Comment by labynocle** [comment] 2022-09-20 18:20
Thank you! let's merge it then :)

**Closed** 2022-09-20 18:22 UTC
